# -*- coding: utf-8 -*-
"""Programming Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFafb-8ud6shXJGY8mWoeIvtIR3hbVAx

# 1. Write a Python Program to Check if a Number is Positive, Negative or Zero?
"""

num = int(input("Enter a number: "))
if num>0:
  print("Number is positive")
elif num==0:
  print("Number is Zero")
else:
  print("number is negative")

"""# 2. Write a Python Program to Check if a Number is Odd or Even?"""

num = int(input("Enter a number: "))
if num%2==0:
  print("Entered number is even")
else:
  print("Entered number is odd")

"""# 3. Write a Python Program to Check Leap Year?"""

year = int(input('Enter year : ')) 
if (year%4 == 0 and year%100 != 0) or (year%400 == 0): 
  print(year, "is a leap year.") 
else: 
  print(f"{year} is not a leap year.")

"""# 4. Write a Python Program to Check Prime Number?"""

num = int(input("Enter a number: "))

# If number is greater than 1
if num > 1:
   # Check if factor exist  
   for i in range(2,num):
       if (num % i) == 0:
           print(num,"is not a prime number")
           break
   else:
       print(num,"is a prime number")
       
# Else if the input number is less than or equal to 1
else:
   print(num,"is not a prime number")

"""# 5. Write a Python Program to Print all Prime Numbers in an Interval of 1-10000?"""

start = 1
stop = 10000
print("Prime numbers between", start, "and", stop, "are:")
for val in range(start, stop):
  if val > 1:
    for i in range(2, val):
      if (val % i) == 0:
        break
    else:
      print(val, end=" ")

