# -*- coding: utf-8 -*-
"""Programming Assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T--tMsjJ17d9CSFvr1td_3qjVRBBavA1

# 1. Write a Python program to convert kilometers to miles?
"""

km = 15

# defining conversion factor
conversion_factor = 0.621371

# calculate miles
miles = km * conversion_factor
print('%0.2f km is equal to %0.2f miles' %(km,miles))

"""# 2. Write a Python program to convert Celsius to Fahrenheit?"""

celsius=int(input("Enter the temperature in celcius:"))
f=(celsius*1.8)+32
print("Temperature in farenheit is:",f)

"""# 3. Write a Python program to display calendar?"""

import calendar

print("Enter Year: ")
yy = input()
print("\nEnter Month Number (1-12): ")
mm = input()

y = int(yy)
m = int(mm)
print("\n", calendar.month(y, m))

"""# 4. Write a Python program to solve quadratic equation?"""

import cmath

a = 1
b = 5
c = 6

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))

"""# 5. Write a Python program to swap two variables without temp variable?"""

a = 10
b = 15

a,b = b,a

print(f"after swapping value of a is: {a}")
print(f"after swapping value of b is: {b}")

