# -*- coding: utf-8 -*-
"""Programming Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cs51bka1zel1D5MUEIOCihpJ4kbS--YL

# 1. Write a Python program to print "Hello World"
"""

print("Hello World")

"""# 2. Write a Python program to do arithmetical operations addition and division?"""

a = 10
b = 2

c = a+b
print(f"sum of a and b is: {c}")

d = a//b   # a/b gives floating point where as a//b gives whole number
print(f"division of a and b is: {d}")

"""# 3. Write a Python program to find the area of a triangle?"""

a = int(input("Enter the value of 1st side: "))
b = int(input("Enter the value of 2nd side: "))
c = int(input("Enter the value of 3rd side: "))

s = (a+b+c)/2   # calculate semi perimeter

#area of triangle

area = (s*(s-a)*(s-b)*(s-c))**0.5 

print(f"Area of a Triangle is: {area}")

"""# 4. Write a Python program to swap two variables?"""

x = 10
y = 20

# creating temporary variable and swapping
temp = x
x = y
y = temp

print(f"value of x after swapping is: {x}")
print(f"value of y after swapping is: {y}")

#without temporary variable

x = 10
y = 20

x,y = y,x

print(f"value of x after swapping is: {x}")
print(f"value of y after swapping is: {y}")

"""# 5. Write a Python program to generate a random number?"""

import random

num = random.random()
print(num)

import random

print(random.randint(1,101))

import random

print(random.randint(1,101))

import random

print(random.randint(1,101))

"""Above are few examples for random numbers, with same program output differs as everytime new random number is generated."""

